### ISSUE TITLE
Actor crashed! Reel::StateError

### ISSUE THREAD

**Issue by mighe** [kenichi/angelo#21]
At least twice Angelo crashed with the following stack trace:

```
E, [2014-12-01T07:36:36.555571 #9954] ERROR -- : Actor crashed!
Reel::StateError: already processing a request
	/home/koala/.rvm/gems/ruby-2.1.0@ufficio/gems/reel-0.5.0/lib/reel/connection.rb:55:in `request'
	/home/koala/.rvm/gems/ruby-2.1.0@ufficio/gems/reel-0.5.0/lib/reel/connection.rb:72:in `each_request'
	/home/koala/.rvm/gems/ruby-2.1.0@ufficio/gems/angelo-0.2.4/lib/angelo/server.rb:23:in `on_connection'
	/home/koala/.rvm/gems/ruby-2.1.0@ufficio/gems/reel-0.5.0/lib/reel/server.rb:56:in `call'
	/home/koala/.rvm/gems/ruby-2.1.0@ufficio/gems/reel-0.5.0/lib/reel/server.rb:56:in `handle_connection'
	/home/koala/.rvm/gems/ruby-2.1.0@ufficio/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/home/koala/.rvm/gems/ruby-2.1.0@ufficio/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/home/koala/.rvm/gems/ruby-2.1.0@ufficio/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
	/home/koala/.rvm/gems/ruby-2.1.0@ufficio/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/home/koala/.rvm/gems/ruby-2.1.0@ufficio/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/home/koala/.rvm/gems/ruby-2.1.0@ufficio/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/home/koala/.rvm/gems/ruby-2.1.0@ufficio/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/home/koala/.rvm/gems/ruby-2.1.0@ufficio/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

It seems somehow related to those Reel issues: https://github.com/celluloid/reel/issues/150 and https://github.com/celluloid/reel/issues/146

Do you have any idea?

(Yes, I did not update yet that machine to Angelo 0.3.2, but AFAIK you did not change anything about request management... I'm going to update it asap, anyway)

**Comment by mighe** [comment]
Hi @kenichi , we made same other test and found out it is a Reel problem (see the referenced issue).
To reproduce it in Angelo just run the following code:

```ruby
require 'angelo'

class AngeloStressTest < Angelo::Base
  public_dir 'assets' 
end

AngeloStressTest.run!
```

And try to download with your browser (or `wget`) a very big file: during this process stop your browser and it will make you process crash.

Of course it happens also with smaller file, it is just harder to reproduce (that is why I had so many problem to reproduce this issue when it occurred the first time)

**Comment by kenichi** [comment]
@mighe i can repro that [issue](https://github.com/celluloid/reel/issues/164). that sounds like an epic pain to track down, and it also sounds like [others](https://github.com/celluoid/reel/issues/163) are having similar problems. i'm going to leave this issue open until those are closed so angelo users that may hit this can track back to the main problem. thanks again!

**Comment by tarcieri** [comment]
https://github.com/celluloid/reel/pull/163 has a potential fix if any of you would like to try it out

**Comment by mighe** [comment]
@tarcieri you say that the request should be fully consumed.
The only way to partially consume it is using `Reel::Request::Body#readpartial`?
I'm asking this because Angelo logs `method`, `url` and `version` *after* every request ( [code is here](https://github.com/kenichi/angelo/blob/master/lib/angelo.rb#L81) ), and I'm wondering if this can cause that pipeline error.
Thank you!

**Comment by kenichi** [comment]
@mighe @tarcieri i have verified the issue in angelo, adapting the example code from 164:

```ruby
class MyServer < Angelo::Base
  get '/' do
    resp = 'HELLO!!! ' * 10E6
  end
end
```

^C-ing curl in the middle causes the `Reel::StateError: already processing a request` and if i switch to loading reel from artcom/master, everything seems to work great. i can cancel requests and re-request over and over again without seeing the StateError.

:+1:

**Comment by tarcieri** [comment]
It's merged now

**Comment by kenichi** [comment]
@mighe if running with reel from master works for you, i'll close this

**Comment by mighe** [comment]
Ok, let's wait for the Reel version :+1: 
Thank you @kenichi !
