### ISSUE TITLE
Angelo crashes using reel 0.6.x

### ISSUE THREAD

**Issue by mighe** [kenichi/angelo#52]
Hi @kenichi, I was trying angelo with reel 0.6.0.pre1 and I get the following error:

```ruby
NameError: uninitialized constant WebSocket::Message
	/xxx/angelo-ef0d4892d865/lib/angelo/base.rb:274:in `block (3 levels) in <class:Base>'
	/xxx//angelo-ef0d4892d865/lib/angelo/stash.rb:88:in `block in all_each'
	/xxx/angelo-ef0d4892d865/lib/angelo/stash.rb:86:in `each'
	/xxx/angelo-ef0d4892d865/lib/angelo/stash.rb:86:in `all_each'
	/xxx/angelo-ef0d4892d865/lib/angelo/base.rb:273:in `block (2 levels) in <class:Base>'
```

the problem is [here](https://github.com/kenichi/angelo/blob/master/lib/angelo/base.rb#L274): the code is using a class from the old websocket parser, that has been removed with the websocket-driver integration.

**Comment by kenichi** [comment]
ah, it looks like the new websocket-driver stuff does not expose the driver. since websocket-driver [has its own ping](https://github.com/faye/websocket-driver-ruby#driverpingstring---callback), we should attempt to use that, eh?

**Comment by kenichi** [comment]
whoa, the new stuff depends on rack and uses Rack::MockRequest?

**Comment by digitalextremist** [comment]
I see this too, and it bothered me. It's coming over by `websocket-driver` as you said. I've not wanted `Rack` anywhere near `Reel` or any DSL it supports. I will look into this also.

**Comment by mighe** [comment]
@digitalextremist do you think it could be useful to have a `ping` method exposed by Reel?
At the moment the only way @kenichi has is to use directly a Reel dependency and this could lead to unexpected problems in the future (like this one).
If pinging a websocket is a useful feature for many developers, having it integrated in Reel is probably the best thing.

**Comment by digitalextremist** [comment]
@mighe we can expose `ping` ( forwarding to `ping` on `@driver` ) no problem.

**Comment by kenichi** [comment]
my immediate fix was to add :driver to the attr_accessor list, but then i saw the mockrequest and went down a rabbit hole of trying to make reel work without that.

**Comment by kenichi** [comment]
@digitalextremist :+1:

**Comment by digitalextremist** [comment]
Yeah I am going to make it work without `Rack` again. I swear there should be a `C` in front of `Rack` because every now and then someone keeps getting us hooked again. And it's all in good fun and everyone is having a rad party committing stuff, and then it's like :bomb: `Rack` reappeared muahahaha

**Comment by kenichi** [comment]
@digitalextremist @mighe see https://github.com/celluloid/reel/pull/188

**Comment by kenichi** [comment]
see also https://github.com/kenichi/angelo/compare/reel_0.6

**Comment by digitalextremist** [comment]
If we clean this up and make sure it's solid, I'll post a `pre2` with this for you, while we wait on `UNIX` sockets.

**Comment by kenichi** [comment]
much has been done as a result of this issue, thanks @mighe.
