### ISSUE TITLE
How to start a supervised server?

### ISSUE THREAD

**Issue by pinyin** [kenichi/angelo#55]
Hi,

Thanks for the elegant work.

It seems that `Angelo::Base.run()` uses `Angelo::Server.new` to start a new server instance, so I cannot call `Angelo::Server.supervise_as` manually like using other Celluloid actors. 

Is there a recommended way to make a supervised server always available in `Celluloid::Actor[]`?

**Comment by kenichi** [comment]
@pinyin thank you! there wasn't one, but what do you think about this?

https://github.com/kenichi/angelo/compare/supervise

used something like this:

```ruby
require 'angelo'
class S < Angelo::Base
  get '/' do
    ''
  end
end
s = S.run S.addr, S.port, supervise_as: :s
puts "supervised: #{Celluloid::Actor[:s]}"
sleep
```

makes me want to change the api of Base#run and #run! to take opts hash only...

**Comment by digitalextremist** [comment]
@kenichi and make sure you anticipate `0.17.0` where `supervise_as` is no longer used!

**Comment by kenichi** [comment]
@digitalextremist ah good to know. 0.17.0 is huge, can you point me to any specifics about this?

**Comment by digitalextremist** [comment]
Well, for one, supervision moved to its own gem: `celluloid-supervision` ... but as of now, `0.17.0` includes that gem out-of-the-box. In the future, it may not. Doesn't hurt to include that gem then.

As of now, you need to add `submodules: true` and use github in your `Gemfile` ...

As for specific syntax, you will be using `as: :name` or `name: :name` ( an alias ) ... and using `#supervise`

**Comment by pinyin** [comment]
Ah that's super fast!

Thanks. My issue is closed.
