### ISSUE TITLE
"main" style breaks with ruby 2.3.1

### ISSUE THREAD

**Issue by kenichi** [kenichi/angelo#67]
this [commit](https://github.com/ruby/ruby/commit/986fb559613c6bd6a76424e08f0847a7e9cd90de) breaks the "main" style feature added by @tommay because it makes `Forwardable` call `method_defined?` which is not present on `main`.

tried replacing the forward/def_delegators stuff in `lib/angelo/main.rb` with this but am running into errors i'm not understanding immediately:

```ruby
  Angelo::Base::DSL.instance_methods.each do |bim|
    define_method bim do |*a|
      @angelo_app.__send__ bim, *a
    end
  end
```

**Comment by tommay** [comment]
I might be able to spend some cycles on this.

**Comment by kenichi** [comment]
i'm dumb and forgot that `*a` doesn't swallow blocks. doing this:

```ruby
  Angelo::Base::DSL.instance_methods.each do |bim|
    define_method bim do |*a, &block|
      @angelo_app.__send__ bim, *a, &block
    end
  end
```

makes it "work" but helpers still fails. 😕

**Comment by kenichi** [comment]
i wound up using `define_singleton_method` which made the main only test pass. let me know if that doesn't sound correct.
