### ISSUE TITLE
Support for PATCH

### ISSUE THREAD

**Issue by tenyo** [kenichi/angelo#78]
I've been using Angelo for a while now and I just noticed it doesn't support the PATCH HTTP verb. Is this on purpose? I can try submitting a PR but wanted to check first.

**Comment by kenichi** [comment]
Hello @tenyo and thanks for using Angelo! re: PATCH I don't remember a specific reason for not including it, I must not have needed it at the time! If you feel like submitting a PR to add support for that, I'd be happy to review and make a new release.

**Comment by tenyo** [comment]
Thanks, @kenichi! I just opened a PR for this.

**Comment by kenichi** [comment]
fixed by #79
